name: dotnet build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - run: git checkout HEAD^
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore .NET Packages
        run: dotnet restore
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Build .NET Solution
        run: dotnet build --configuration Release --no-restore
      - name: Pack .NET Solution
        run: dotnet pack --no-build --output pack/
      - name: Publish .NET Solution to GitHub Packages
        continue-on-error: true
        run: dotnet nuget push pack/* --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Publish .NET Solution to NuGet.org
        continue-on-error: true
        run: dotnet nuget push pack/* --api-key ${{ secrets.NUGET_ORG_KEY }} --source nuget
        
        
